import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Table from '../components/table'
import Form from '../components/Form'
import { useState } from 'react'

export default function Home() {
    const [visible, setVisible] = useState(false)
    const handler = () => {
        setVisible(!visible)
    }
    return ( <
        section >
        <
        Head >
        <
        title > Create Next App < /title> <
        meta name = "description"
        content = "Generated by create next app" / >
        <
        link rel = "icon"
        href = "/favicon.ico" / >
        <
        /Head>

        <
        main >
        <
        h1 > Employee Management System < /h1> <
        div >
        <
        div >
        <
        button onClick = { handler } > Add Employee < /button> <
        /div>



        <
        /div>


        { visible ? < Form > < /Form> : <></ > }


        <
        div className = "container" >
        <
        Table > < /Table> <
        /div> <
        /main>


        <
        /section>
    )
}